### ISSUE TITLE
perf-postprocess error with field count in SPR CPU

### ISSUE THREAD

**Issue by rb2048** [intel/PerfSpect#15]
I recently successfully gathered perf stat csv with perf-collect command. 
And tried to use perf-postprocess command to generate metric out csv and html files but it failed with following error.

Traceback (most recent call last):
  File "perf-postprocess.py", line 1497, in <module>
  File "perf-postprocess.py", line 772, in write_perf_tmp_output
  File "pandas/util/_decorators.py", line 211, in wrapper
  File "pandas/util/_decorators.py", line 331, in wrapper
  File "pandas/io/parsers/readers.py", line 950, in read_csv
  File "pandas/io/parsers/readers.py", line 611, in _read
  File "pandas/io/parsers/readers.py", line 1778, in read
  File "pandas/io/parsers/c_parser_wrapper.py", line 230, in read
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
**pandas.errors.ParserError: Error tokenizing data. C error: Expected 8 fields in line 171, saw 10**

I compared the output file of perf-collect file with ICX CPU files and found that the field count of ICX csv file was 8 but the field count of SPR csv file was 10. Plz check and let me know how to fix it. Thanks.

**Comment by rb2048** [comment]
Hi, 
OS : CentOS Stream release 9
Kernel : 5.14.0-283.el9.x86_64
Perf : perf version 5.14.0-283.el9.x86_64

**Comment by rb2048** [comment]
I also retested with perf version 6.1.rc2.gb229b6ca5abb and got same results.

**Comment by rb2048** [comment]
Hi, today I found my mistake of dealing with latest perfspect. 
I got error when I use older version of perf-collect and latest version of perf-postprocess. 
I was able to get the desired result by deleting the old version of the perf-collect file and retesting with the latest version.

**Comment by hilldani** [comment]
Glad the recent version worked for you!
